### ISSUE TITLE
Robot can be in multiple robot states.

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-InfiniteRecharge2020#1]
Button configuration allows for multiple robot states to be true. For example, both of these triggers would fire off if both the shooter and panel mode buttons are being pressed.

https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/23bb2e29faf455437f52855c6850ee96e8774e55/src/main/java/frc/robot/RobotContainer.java#L68

https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/23bb2e29faf455437f52855c6850ee96e8774e55/src/main/java/frc/robot/RobotContainer.java#L78

Robot state should be written down somewhere and referenced. 

```
 Trigger shooter_SpinFlywheels = new Trigger() {
    @Override
    public boolean get() { return (robotState == "Shoot") && x.get(); }
  };
```
A subsystem can handle this as a default command that sets "collect" as the global state and then is overwritten by more specific commands.

**Comment by Rodney-Lewis** [comment]
Possible solution...

RobotContainer configures state buttons  for whenHeld (note: whileHeld WILL NOT have the same behavior).
```
public class RobotContainer {
  private static XboxController controller = new XboxController(0);
  private static JoystickButton bumperLeft = new JoystickButton(controller, XboxController.Button.kBumperLeft.value);
  private static JoystickButton panelMode = new JoystickButton(controller, XboxController.Button.kX.value); // start button
  private static JoystickButton shootMode = new JoystickButton(controller, XboxController.Button.kY.value); // back button
  private static JoystickButton climbMode = new JoystickButton(controller, XboxController.Button.kA.value); // lt button

  static String robotState;

  private static ExampleSubsystem s_example = new ExampleSubsystem();

  Trigger shoot = new Trigger() {
    @Override
    public boolean get() { return (robotState == "shoot") && bumperLeft.get(); }
  };

  public RobotContainer() {
    configureButtonBindings();
    robotState = "collect";
  }

  private void configureButtonBindings() {
    panelMode.whenHeld(new SetState("panel"));
    shootMode.whenHeld(new SetState("shoot"));
    climbMode.whenHeld(new SetState("climb"));
    shoot.whenActive(new ExampleCommand(s_example).withTimeout(5));
  }

  public static String getRobotState() {
    return robotState;
  }
}

```

WhenHeld, end doesn't run. So the command initializes and then suspends. WhenReleased, end will run.
```
public class SetState extends CommandBase {

  String state;

  public SetState(String state) {
    this.state = state;
  }

  @Override
  public void initialize() {
    RobotContainer.robotState = this.state;
    SmartDashboard.putString("State", RobotContainer.robotState);
    SmartDashboard.putString("Input state", this.state);
  }

  @Override
  public void end(boolean interrupted) {
    RobotContainer.robotState = "collect";
    SmartDashboard.putString("State", RobotContainer.robotState);
    SmartDashboard.putString("Input state", this.state);
  }
}
```

Example command.
```
public class ExampleCommand extends CommandBase {
  @SuppressWarnings({"PMD.UnusedPrivateField", "PMD.SingularField"})
  private final ExampleSubsystem m_subsystem;

  public ExampleCommand(ExampleSubsystem subsystem) {
    m_subsystem = subsystem;
    addRequirements(subsystem);
  }

  @Override
  public void initialize() {
    SmartDashboard.putString("Command Run", "Init");
  }

  @Override
  public void execute() {
    SmartDashboard.putString("Command Run", "BANG");
  }

  @Override
  public void end(boolean interrupted) {
    SmartDashboard.putString("Command Run", "End");
  }

  @Override
  public boolean isFinished() {
    return false;
  }
}

```

**Comment by Rodney-Lewis** [comment]
Note: WithTimeout() in the constructor of a command throws a NPE.

```
public ExampleCommand(ExampleSubsystem subsystem) {
    m_subsystem = subsystem;
    withTimeout(5);
    addRequirements(subsystem);
  }
```

> Error at frc.robot.Robot.robotPeriodic(Robot.java:49): Unhandled excepWatchdog not fed within tion: 0.020000jas
> va.lang.IllegalArgumentException: A command that is part of a command group cannot be independently scheduled
>         at edu.wpi.first.wpilibj2.command.Command.schedule(Command.java:251)
>         at edu.wpi.first.wpilibj2.command.button.Trigger$1.run(Trigger.java:80)
>         at edu.wpi.first.wpilibj2.command.CommandScheduler.run(CommandScheduler.java:234)
>         at frc.robot.Robot.robotPeriodic(Robot.java:49)
>         at edu.wpi.first.wpilibj.IterativeRobotBase.loopFunc(IterativeRobotBase.java:258)
>         at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:82)
>         at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:276)
>         at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:329)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> 
> Warning at edu.wpi.first.wpilibj.IterativeRobotBase.printLoopOverrunMessage(IterativeRobotBase.java:276): Loop time of 0.02s overrun  
> 
> Warning at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:291): Robots should not quit, but yours did!
> Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:293): The startCompetition() method (or methods called by it) should 
> have handled the exception above.
> [phoenix] Library could NOT shutdown cleanly
> 

The following works okay though.

```
public ExampleCommand(ExampleSubsystem subsystem) {
    m_subsystem = subsystem;
    addRequirements(subsystem);
  }

shoot.whenActive(new ExampleCommand(s_example).withTimeout(5));

```

**Comment by Rodney-Lewis** [comment]
Resolved.
